apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - image: quay.io/coreos/etcd:v3.5.1
        name: etcd
        command:
        - /usr/local/bin/etcd
        - --advertise-client-urls=https://$(POD_NAME).etcd.$(POD_NAMESPACE).svc.cluster.local:2379
        - --cert-file=/opt/certs/server/tls.crt
        - --data-dir=/data
        - --initial-advertise-peer-urls=https://$(POD_NAME).etcd.$(POD_NAMESPACE).svc.cluster.local:2380
        - --initial-cluster=etcd-0=https://etcd-0.etcd.$(POD_NAMESPACE).svc.cluster.local:2380,etcd-1=https://etcd-1.etcd.$(POD_NAMESPACE).svc.cluster.local:2380,etcd-2=https://etcd-2.etcd.$(POD_NAMESPACE).svc.cluster.local:2380
        - --initial-cluster-state=new
        - --key-file=/opt/certs/server/tls.key
        - --listen-client-urls=https://0.0.0.0:2379
        - --listen-metrics-urls=http://0.0.0.0:2381
        - --listen-peer-urls=https://0.0.0.0:2380
        - --name=$(POD_NAME)
        - --peer-cert-file=/opt/certs/peer/tls.crt
        - --peer-key-file=/opt/certs/peer/tls.key
        - --peer-trusted-ca-file=/opt/certs/peer/ca.crt
        - --trusted-ca-file=/opt/certs/server/ca.crt
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 60
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        - containerPort: 2381
          name: metrics
        volumeMounts:
        - name: data
          mountPath: /data
        - name: peer-cert
          mountPath: /opt/certs/peer
        - name: server-cert
          mountPath: /opt/certs/server
      volumes:
      - name: peer-cert
        secret:
          secretName: etcd-peer
      - name: server-cert
        secret:
          secretName: etcd-server
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  ports:
  - name: client
    port: 2379
    targetPort: client
  selector:
    app: etcd
